package views;

import connectionDB.koneksi;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.plaf.RootPaneUI;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
//import views.about;
/**
 *
 * @author KELOMPOK 1
 */
public class MenuUtama extends javax.swing.JFrame {
        
    // waktu sekarang 
     private void setJam(){
        ActionListener listener = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent evt) {
                jam.setText(new WaktuSekarang().getWkt());
            }
        };
        new Timer(1000, listener).start();
    }
    // penutup waktu sekarang
     
    // frame maks dan geser panel
    static boolean maximixed = true;
    int xMouse;
    int yMouse;
// penutup frame maks dan geser panel
    

    
    public MenuUtama() {
        initComponents();
        setJam();
        panelMasterData.setVisible(false);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        labelNama = new javax.swing.JLabel();
        btnMaximize = new javax.swing.JButton();
        btnMinimize = new javax.swing.JButton();
        panelMenu = new javax.swing.JPanel();
        btnMasterData = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        panelJam = new javax.swing.JPanel();
        tgl = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();
        jPanel1 = new views.Background();
        btnAbout = new javax.swing.JButton();
        panelMasterData = new javax.swing.JPanel();
        btnTataUsaha = new javax.swing.JButton();
        btnGuru = new javax.swing.JButton();
        btnSiswa = new javax.swing.JButton();
        btnJurusan = new javax.swing.JButton();
        btnMapel = new javax.swing.JButton();
        btnKelas = new javax.swing.JButton();
        panelTransaksi = new javax.swing.JPanel();
        btnInputNilai = new javax.swing.JButton();
        btnPembayaranSeragam = new javax.swing.JButton();
        panelLaporan = new javax.swing.JPanel();
        btnLapDataSiswa = new javax.swing.JButton();
        btnLapDataGuru = new javax.swing.JButton();
        btnLapTU = new javax.swing.JButton();
        btnLapNilai = new javax.swing.JButton();
        btnLapSeragam = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelUtama.setBackground(new java.awt.Color(204, 204, 204));
        panelUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUtamaMouseClicked(evt);
            }
        });

        panelHeader.setBackground(new java.awt.Color(0, 0, 255));

        btnClose.setBackground(new java.awt.Color(0, 0, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_30px_4.png"))); // NOI18N
        btnClose.setContentAreaFilled(false);
        btnClose.setOpaque(true);
        btnClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_30px_5.png"))); // NOI18N
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseMouseExited(evt);
            }
        });
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        labelNama.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelNama.setForeground(new java.awt.Color(255, 255, 255));
        labelNama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNama.setText("Aplikasi Akademik SMK Negeri 19 Jakarta");
        labelNama.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                labelNamaMouseDragged(evt);
            }
        });
        labelNama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                labelNamaMousePressed(evt);
            }
        });

        btnMaximize.setBackground(new java.awt.Color(102, 102, 102));
        btnMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Maximize_Window_30px.png"))); // NOI18N
        btnMaximize.setContentAreaFilled(false);
        btnMaximize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Maximize_Window_30px_1.png"))); // NOI18N
        btnMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximizeMouseClicked(evt);
            }
        });

        btnMinimize.setBackground(new java.awt.Color(204, 204, 204));
        btnMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Minimize_Window_30px.png"))); // NOI18N
        btnMinimize.setContentAreaFilled(false);
        btnMinimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Minimize_Window_30px_1.png"))); // NOI18N
        btnMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMinimizeMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(btnMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnMaximize, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
            .addComponent(btnMaximize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMinimize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelMenu.setBackground(new java.awt.Color(0, 153, 153));

        btnMasterData.setBackground(new java.awt.Color(0, 153, 153));
        btnMasterData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMasterData.setForeground(new java.awt.Color(255, 255, 255));
        btnMasterData.setText("  Master Data");
        btnMasterData.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMasterData.setContentAreaFilled(false);
        btnMasterData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasterData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMasterData.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnMasterData.setOpaque(true);
        btnMasterData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasterDataMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMasterDataMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMasterDataMouseExited(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(0, 153, 153));
        btnTransaksi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaksi.setText("  Data Transaksi");
        btnTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnTransaksi.setContentAreaFilled(false);
        btnTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTransaksi.setOpaque(true);
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
        });

        btnLaporan.setBackground(new java.awt.Color(0, 153, 153));
        btnLaporan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporan.setText("  Laporan");
        btnLaporan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLaporan.setContentAreaFilled(false);
        btnLaporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLaporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLaporan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLaporan.setOpaque(true);
        btnLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLaporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLaporanMouseExited(evt);
            }
        });

        panelJam.setBackground(new java.awt.Color(0, 0, 204));

        tgl.setBackground(new java.awt.Color(0, 0, 255));
        tgl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        tgl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tgl.setOpaque(true);

        jam.setBackground(new java.awt.Color(0, 0, 255));
        jam.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jam.setForeground(new java.awt.Color(255, 255, 255));
        jam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jam.setOpaque(true);

        javax.swing.GroupLayout panelJamLayout = new javax.swing.GroupLayout(panelJam);
        panelJam.setLayout(panelJamLayout);
        panelJamLayout.setHorizontalGroup(
            panelJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tgl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .addComponent(jam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelJamLayout.setVerticalGroup(
            panelJamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelJamLayout.createSequentialGroup()
                .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tgl.setText(new WaktuSekarang().getTgl());
        tgl.setPreferredSize(new java.awt.Dimension(120,22));
        jam.setText(new WaktuSekarang().getWkt());
        jam.setPreferredSize(new java.awt.Dimension(100,22));

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        btnAbout.setBackground(new java.awt.Color(0, 153, 153));
        btnAbout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(255, 255, 255));
        btnAbout.setText("  About");
        btnAbout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAbout.setContentAreaFilled(false);
        btnAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAbout.setOpaque(true);
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAboutMouseExited(evt);
            }
        });
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMasterData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btnTransaksi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(btnLaporan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(panelJam, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAbout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelMasterData.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnTataUsaha.setBackground(new java.awt.Color(0, 153, 153));
        btnTataUsaha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTataUsaha.setForeground(new java.awt.Color(255, 255, 255));
        btnTataUsaha.setText("  > Data Tata Usaha");
        btnTataUsaha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnTataUsaha.setContentAreaFilled(false);
        btnTataUsaha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTataUsaha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnTataUsaha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTataUsaha.setOpaque(true);
        btnTataUsaha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTataUsahaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTataUsahaMouseExited(evt);
            }
        });
        btnTataUsaha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTataUsahaActionPerformed(evt);
            }
        });

        btnGuru.setBackground(new java.awt.Color(0, 153, 153));
        btnGuru.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuru.setForeground(new java.awt.Color(255, 255, 255));
        btnGuru.setText("  > Data Guru");
        btnGuru.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGuru.setContentAreaFilled(false);
        btnGuru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGuru.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuru.setOpaque(true);
        btnGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuruMouseExited(evt);
            }
        });
        btnGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuruActionPerformed(evt);
            }
        });

        btnSiswa.setBackground(new java.awt.Color(0, 153, 153));
        btnSiswa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSiswa.setForeground(new java.awt.Color(255, 255, 255));
        btnSiswa.setText("  > Data Siswa/i");
        btnSiswa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSiswa.setContentAreaFilled(false);
        btnSiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSiswa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSiswa.setOpaque(true);
        btnSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSiswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSiswaMouseExited(evt);
            }
        });
        btnSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiswaActionPerformed(evt);
            }
        });

        btnJurusan.setBackground(new java.awt.Color(0, 153, 153));
        btnJurusan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnJurusan.setForeground(new java.awt.Color(255, 255, 255));
        btnJurusan.setText("  > Data Jurusan");
        btnJurusan.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnJurusan.setContentAreaFilled(false);
        btnJurusan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnJurusan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnJurusan.setOpaque(true);
        btnJurusan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnJurusanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnJurusanMouseExited(evt);
            }
        });
        btnJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJurusanActionPerformed(evt);
            }
        });

        btnMapel.setBackground(new java.awt.Color(0, 153, 153));
        btnMapel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMapel.setForeground(new java.awt.Color(255, 255, 255));
        btnMapel.setText("  > Data Mata Pelajaran");
        btnMapel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnMapel.setContentAreaFilled(false);
        btnMapel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMapel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnMapel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMapel.setOpaque(true);
        btnMapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMapelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMapelMouseExited(evt);
            }
        });
        btnMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapelActionPerformed(evt);
            }
        });

        btnKelas.setBackground(new java.awt.Color(0, 153, 153));
        btnKelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKelas.setForeground(new java.awt.Color(255, 255, 255));
        btnKelas.setText("  > Data Kelas");
        btnKelas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnKelas.setContentAreaFilled(false);
        btnKelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnKelas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKelas.setOpaque(true);
        btnKelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKelasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKelasMouseExited(evt);
            }
        });
        btnKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMasterDataLayout = new javax.swing.GroupLayout(panelMasterData);
        panelMasterData.setLayout(panelMasterDataLayout);
        panelMasterDataLayout.setHorizontalGroup(
            panelMasterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTataUsaha, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(btnGuru, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(btnSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(btnJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(btnMapel, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(btnKelas, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        panelMasterDataLayout.setVerticalGroup(
            panelMasterDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMasterDataLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnTataUsaha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTransaksi.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnInputNilai.setBackground(new java.awt.Color(0, 153, 153));
        btnInputNilai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInputNilai.setForeground(new java.awt.Color(255, 255, 255));
        btnInputNilai.setText("  > Input Nilai");
        btnInputNilai.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnInputNilai.setContentAreaFilled(false);
        btnInputNilai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInputNilai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInputNilai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnInputNilai.setOpaque(true);
        btnInputNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInputNilaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInputNilaiMouseExited(evt);
            }
        });
        btnInputNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputNilaiActionPerformed(evt);
            }
        });

        btnPembayaranSeragam.setBackground(new java.awt.Color(0, 153, 153));
        btnPembayaranSeragam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPembayaranSeragam.setForeground(new java.awt.Color(255, 255, 255));
        btnPembayaranSeragam.setText("  > Pembelian Seragam Sekolah");
        btnPembayaranSeragam.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnPembayaranSeragam.setContentAreaFilled(false);
        btnPembayaranSeragam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPembayaranSeragam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPembayaranSeragam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPembayaranSeragam.setOpaque(true);
        btnPembayaranSeragam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPembayaranSeragamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPembayaranSeragamMouseExited(evt);
            }
        });
        btnPembayaranSeragam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranSeragamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransaksiLayout = new javax.swing.GroupLayout(panelTransaksi);
        panelTransaksi.setLayout(panelTransaksiLayout);
        panelTransaksiLayout.setHorizontalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPembayaranSeragam, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnInputNilai, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelTransaksiLayout.setVerticalGroup(
            panelTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransaksiLayout.createSequentialGroup()
                .addComponent(btnInputNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnPembayaranSeragam, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelLaporan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnLapDataSiswa.setBackground(new java.awt.Color(0, 153, 153));
        btnLapDataSiswa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLapDataSiswa.setForeground(new java.awt.Color(255, 255, 255));
        btnLapDataSiswa.setText("  > Laporan Data Siswa");
        btnLapDataSiswa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLapDataSiswa.setContentAreaFilled(false);
        btnLapDataSiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLapDataSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapDataSiswa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLapDataSiswa.setOpaque(true);
        btnLapDataSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLapDataSiswaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLapDataSiswaMouseExited(evt);
            }
        });
        btnLapDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapDataSiswaActionPerformed(evt);
            }
        });

        btnLapDataGuru.setBackground(new java.awt.Color(0, 153, 153));
        btnLapDataGuru.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLapDataGuru.setForeground(new java.awt.Color(255, 255, 255));
        btnLapDataGuru.setText("  > Laporan Data Guru");
        btnLapDataGuru.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLapDataGuru.setContentAreaFilled(false);
        btnLapDataGuru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLapDataGuru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapDataGuru.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLapDataGuru.setOpaque(true);
        btnLapDataGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLapDataGuruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLapDataGuruMouseExited(evt);
            }
        });
        btnLapDataGuru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapDataGuruActionPerformed(evt);
            }
        });

        btnLapTU.setBackground(new java.awt.Color(0, 153, 153));
        btnLapTU.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLapTU.setForeground(new java.awt.Color(255, 255, 255));
        btnLapTU.setText("  > Laporan Data Tata Usaha");
        btnLapTU.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLapTU.setContentAreaFilled(false);
        btnLapTU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLapTU.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapTU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLapTU.setOpaque(true);
        btnLapTU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLapTUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLapTUMouseExited(evt);
            }
        });
        btnLapTU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapTUActionPerformed(evt);
            }
        });

        btnLapNilai.setBackground(new java.awt.Color(0, 153, 153));
        btnLapNilai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLapNilai.setForeground(new java.awt.Color(255, 255, 255));
        btnLapNilai.setText("  > Laporan Nilai Siswa");
        btnLapNilai.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLapNilai.setContentAreaFilled(false);
        btnLapNilai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLapNilai.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapNilai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLapNilai.setOpaque(true);
        btnLapNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLapNilaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLapNilaiMouseExited(evt);
            }
        });
        btnLapNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapNilaiActionPerformed(evt);
            }
        });

        btnLapSeragam.setBackground(new java.awt.Color(0, 153, 153));
        btnLapSeragam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLapSeragam.setForeground(new java.awt.Color(255, 255, 255));
        btnLapSeragam.setText("  > Laporan Seragam Sekolah");
        btnLapSeragam.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLapSeragam.setContentAreaFilled(false);
        btnLapSeragam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLapSeragam.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLapSeragam.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLapSeragam.setOpaque(true);
        btnLapSeragam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLapSeragamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLapSeragamMouseExited(evt);
            }
        });
        btnLapSeragam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapSeragamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLaporanLayout = new javax.swing.GroupLayout(panelLaporan);
        panelLaporan.setLayout(panelLaporanLayout);
        panelLaporanLayout.setHorizontalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLapDataGuru, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnLapDataSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnLapTU, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnLapNilai, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnLapSeragam, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        panelLaporanLayout.setVerticalGroup(
            panelLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLaporanLayout.createSequentialGroup()
                .addComponent(btnLapDataSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLapDataGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLapTU, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLapNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnLapSeragam, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1617, Short.MAX_VALUE))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addComponent(panelMasterData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(panelTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(panelLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 93, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseEntered
//        btnClose.setBackground(Color.white);
    }//GEN-LAST:event_btnCloseMouseEntered

    private void btnCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseExited
        btnClose.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnCloseMouseExited

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        String ObjButton[] = {"YES","NO"};
        int pilihan = JOptionPane.showOptionDialog(null,"Apakah Anda yakin ingin keluar?", "Message", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE,
                null,ObjButton,ObjButton[1]);
        if(pilihan == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseEntered
        btnMinimize.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_btnMinimizeMouseEntered

    private void btnMasterDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterDataMouseClicked
        panelMasterData.setVisible(true);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_btnMasterDataMouseClicked

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        panelTransaksi.setVisible(true);
        panelMasterData.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseClicked
        panelLaporan.setVisible(true);
        panelTransaksi.setVisible(false);
        panelMasterData.setVisible(false);
    }//GEN-LAST:event_btnLaporanMouseClicked

    private void btnTataUsahaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTataUsahaActionPerformed
        panelMasterData.setVisible(false);
        new MasterDataTataUsaha(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnTataUsahaActionPerformed

    private void panelUtamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtamaMouseClicked
        panelMasterData.setVisible(false);
        panelTransaksi.setVisible(false);
        panelLaporan.setVisible(false);
    }//GEN-LAST:event_panelUtamaMouseClicked

    private void btnMasterDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterDataMouseEntered
        btnMasterData.setForeground(Color.black);
        btnMasterData.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnMasterDataMouseEntered

    private void btnMasterDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasterDataMouseExited
        btnMasterData.setForeground(Color.white);
        btnMasterData.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnMasterDataMouseExited

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
        btnTransaksi.setForeground(Color.black);
        btnTransaksi.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        btnTransaksi.setForeground(Color.white);
        btnTransaksi.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnLaporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseEntered
        btnLaporan.setForeground(Color.black);
        btnLaporan.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnLaporanMouseEntered

    private void btnLaporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanMouseExited
        btnLaporan.setForeground(Color.white);
        btnLaporan.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnLaporanMouseExited

    private void btnTataUsahaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTataUsahaMouseEntered
        btnTataUsaha.setForeground(Color.black);
        btnTataUsaha.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnTataUsahaMouseEntered

    private void btnTataUsahaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTataUsahaMouseExited
        btnTataUsaha.setForeground(Color.white);
        btnTataUsaha.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnTataUsahaMouseExited

    private void btnGuruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuruMouseEntered
        btnGuru.setForeground(Color.black);
        btnGuru.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnGuruMouseEntered

    private void btnGuruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuruMouseExited
        btnGuru.setForeground(Color.white);
        btnGuru.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnGuruMouseExited

    private void btnSiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiswaMouseEntered
        btnSiswa.setForeground(Color.black);
        btnSiswa.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnSiswaMouseEntered

    private void btnSiswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiswaMouseExited
        btnSiswa.setForeground(Color.white);
        btnSiswa.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnSiswaMouseExited

    private void btnJurusanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJurusanMouseEntered
        btnJurusan.setForeground(Color.black);
        btnJurusan.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnJurusanMouseEntered

    private void btnJurusanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJurusanMouseExited
        btnJurusan.setForeground(Color.white);
        btnJurusan.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnJurusanMouseExited

    private void btnInputNilaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputNilaiMouseEntered
        btnInputNilai.setForeground(Color.black);
        btnInputNilai.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnInputNilaiMouseEntered

    private void btnInputNilaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInputNilaiMouseExited
        btnInputNilai.setForeground(Color.white);
        btnInputNilai.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnInputNilaiMouseExited

    private void btnPembayaranSeragamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPembayaranSeragamMouseEntered
        btnPembayaranSeragam.setForeground(Color.black);
        btnPembayaranSeragam.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnPembayaranSeragamMouseEntered

    private void btnPembayaranSeragamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPembayaranSeragamMouseExited
        btnPembayaranSeragam.setForeground(Color.white);
        btnPembayaranSeragam.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnPembayaranSeragamMouseExited

    private void btnLapDataSiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapDataSiswaMouseEntered
        btnLapDataSiswa.setForeground(Color.black);
        btnLapDataSiswa.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnLapDataSiswaMouseEntered

    private void btnLapDataSiswaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapDataSiswaMouseExited
        btnLapDataSiswa.setForeground(Color.white);
        btnLapDataSiswa.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnLapDataSiswaMouseExited

    private void btnLapDataGuruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapDataGuruMouseEntered
        btnLapDataGuru.setForeground(Color.black);
        btnLapDataGuru.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnLapDataGuruMouseEntered

    private void btnLapDataGuruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapDataGuruMouseExited
        btnLapDataGuru.setForeground(Color.white);
        btnLapDataGuru.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnLapDataGuruMouseExited

    private void btnLapTUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapTUMouseEntered
        btnLapTU.setForeground(Color.black);
        btnLapTU.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnLapTUMouseEntered

    private void btnLapTUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapTUMouseExited
        btnLapTU.setForeground(Color.white);
        btnLapTU.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnLapTUMouseExited

    private void btnJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJurusanActionPerformed
        panelMasterData.setVisible(false);
        new MasterDataJurusan(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnJurusanActionPerformed

    private void btnMaximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximizeMouseClicked
        if(maximixed){
            MenuUtama.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment env = GraphicsEnvironment.getLocalGraphicsEnvironment();
            MenuUtama.this.setMaximizedBounds(env.getMaximumWindowBounds());
            maximixed = false;
        } else {
            setExtendedState(JFrame.NORMAL);
            maximixed = true;
        }
    }//GEN-LAST:event_btnMaximizeMouseClicked

    private void btnMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimizeMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizeMouseClicked

    private void labelNamaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNamaMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_labelNamaMousePressed

    private void labelNamaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelNamaMouseDragged
        if(maximixed){
            int x = evt.getXOnScreen();
            int y = evt.getYOnScreen();
            this.setLocation(x - xMouse, y - yMouse);
        }
    }//GEN-LAST:event_labelNamaMouseDragged

    private void btnSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiswaActionPerformed
        panelMasterData.setVisible(false);
        new MasterDataSiswa(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnSiswaActionPerformed

    private void btnGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuruActionPerformed
        panelMasterData.setVisible(false);
        new MasterDataGuru(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnGuruActionPerformed

    private void btnInputNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputNilaiActionPerformed
        panelTransaksi.setVisible(false);
        new TransaksiInputNilai(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnInputNilaiActionPerformed

    private void btnPembayaranSeragamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranSeragamActionPerformed
        panelTransaksi.setVisible(false);
        new TransaksiSeragam(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnPembayaranSeragamActionPerformed

    private void btnLapDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapDataSiswaActionPerformed
        panelLaporan.setVisible(false);
//        new laporanBarangMasuk(this, rootPaneCheckingEnabled).show();
        try {
            String namaFile = "src/Report/ReportDataSiswa.jasper";
            Connection conn = new koneksi().connect();
            HashMap parameter = new HashMap();
            File report_file = new File(namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameter, conn);
            JasperViewer.viewReport(jasperPrint, false); //coba
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btnLapDataSiswaActionPerformed

    private void btnLapDataGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapDataGuruActionPerformed
        panelLaporan.setVisible(false);
//        new laporanBarangKeluar(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnLapDataGuruActionPerformed

    private void btnLapTUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapTUActionPerformed
        panelLaporan.setVisible(false);
//        new laporanStokBarang(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnLapTUActionPerformed

    private void btnAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseEntered
        btnAbout.setForeground(Color.black);
        btnAbout.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnAboutMouseEntered

    private void btnAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMouseExited
        btnAbout.setForeground(Color.white);
        btnAbout.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnAboutMouseExited

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
//        new about(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnLapNilaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapNilaiMouseEntered
        btnLapNilai.setForeground(Color.black);
        btnLapNilai.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnLapNilaiMouseEntered

    private void btnLapNilaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapNilaiMouseExited
        btnLapNilai.setForeground(Color.white);
        btnLapNilai.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnLapNilaiMouseExited

    private void btnLapNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapNilaiActionPerformed
        panelLaporan.setVisible(false);
//        new laporanDataSupplier(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnLapNilaiActionPerformed

    private void btnMapelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMapelMouseEntered
        // TODO add your handling code here:
        btnMapel.setForeground(Color.black);
        btnMapel.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnMapelMouseEntered

    private void btnMapelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMapelMouseExited
        // TODO add your handling code here:
        btnMapel.setForeground(Color.white);
        btnMapel.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnMapelMouseExited

    private void btnMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapelActionPerformed
        // TODO add your handling code here:
        panelMasterData.setVisible(false);
        new MasterDataMataPelajaran(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnMapelActionPerformed

    private void btnKelasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKelasMouseEntered
        // TODO add your handling code here:
        btnKelas.setForeground(Color.black);
        btnKelas.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnKelasMouseEntered

    private void btnKelasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKelasMouseExited
        // TODO add your handling code here:
        btnKelas.setForeground(Color.white);
        btnKelas.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnKelasMouseExited

    private void btnKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelasActionPerformed
        // TODO add your handling code here:
        panelMasterData.setVisible(false);
        new MasterDataKelas(this, rootPaneCheckingEnabled).show();
    }//GEN-LAST:event_btnKelasActionPerformed

    private void btnLapSeragamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapSeragamMouseEntered
        // TODO add your handling code here:
        btnLapSeragam.setForeground(Color.black);
        btnLapSeragam.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnLapSeragamMouseEntered

    private void btnLapSeragamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLapSeragamMouseExited
        // TODO add your handling code here:
        btnLapSeragam.setForeground(Color.white);
        btnLapSeragam.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_btnLapSeragamMouseExited

    private void btnLapSeragamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapSeragamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLapSeragamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuUtama mn = new MenuUtama();
                mn.setExtendedState(JFrame.MAXIMIZED_BOTH);
                mn.setVisible(true);
            }           
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnGuru;
    private javax.swing.JButton btnInputNilai;
    private javax.swing.JButton btnJurusan;
    private javax.swing.JButton btnKelas;
    private javax.swing.JButton btnLapDataGuru;
    private javax.swing.JButton btnLapDataSiswa;
    private javax.swing.JButton btnLapNilai;
    private javax.swing.JButton btnLapSeragam;
    private javax.swing.JButton btnLapTU;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnMapel;
    private javax.swing.JButton btnMasterData;
    private javax.swing.JButton btnMaximize;
    private javax.swing.JButton btnMinimize;
    private javax.swing.JButton btnPembayaranSeragam;
    private javax.swing.JButton btnSiswa;
    private javax.swing.JButton btnTataUsaha;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jam;
    private javax.swing.JLabel labelNama;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelJam;
    private javax.swing.JPanel panelLaporan;
    private javax.swing.JPanel panelMasterData;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelTransaksi;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JLabel tgl;
    // End of variables declaration//GEN-END:variables
}
