/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import connectionDB.koneksi;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import model.ModelAlternatifSAW;
import static views.MenuUtama.maximixed;
/**
 *
 * @author User
 */
public class NewInputDataAlternatif extends javax.swing.JFrame {

    /**
     * Creates new form NewInputDataAlternatif
     */
    private DecimalFormat nonDecimal = new DecimalFormat("#");
    
    public NewInputDataAlternatif(java.awt.Frame parent, boolean modal) {
        initComponents();
        datatable1();
        datatable2();
    }
    
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    
    protected void aktif(){
        tnis.setEnabled(true);
        tnamasiswa.setEnabled(true);
        c1.setEnabled(true);
        c2.setEnabled(true);
        c3.setEnabled(true);
        c4.setEnabled(true);
        
        tnis.requestFocus();
    }
    
    protected void kosong(){
        tnis.setText("");
        tnamasiswa.setText("");
        c1.setText("");
        c2.setText("");
        c3.setText("");
        c4.setText("");
    }
    
    protected void datatable1(){
    Object [] Baris = {"NO","NIS","NAMA","NILAI RERATA","SIKAP","KEHADIRAN","EKSTRAKULIKULER"};
    tabmode = new DefaultTableModel(null, Baris);
    tabelalternatif1.setModel(tabmode);
    try {
    String sql = "Select * from tb_alternatif1";
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        int nos = 1;
        while (hasil.next()){
            String a = String.valueOf(nos);
            String b = hasil.getString("nis");
            String c = hasil.getString("nama");
            String d = hasil.getString("c1");
            String e = hasil.getString("c2");
            String f = hasil.getString("c3");
            String g = hasil.getString("c4");
            String[] data={a,b,c,d,e,f,g};
            tabmode.addRow(data);
            
            nos++;
        }
    }catch (SQLException e){
        }
    }
    
    protected void datatable2(){
    Object [] Baris = {"NO","NIS","NAMA","NILAI RERATA","SIKAP","KEHADIRAN","ESTRAKULIKULER"};
    tabmode = new DefaultTableModel(null, Baris);
    tabelalternatif2.setModel(tabmode);
    try {
    String sql = "Select * from tb_alternatif2";
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        int nos = 1;
        while (hasil.next()){
            String a = String.valueOf(nos);
            String b = hasil.getString("nis");
            String c = hasil.getString("nama");
            String d = hasil.getString("c1");
            String e = hasil.getString("c2");
            String f = hasil.getString("c3");
            String g = hasil.getString("c4");
            String[] data={a,b,c,d,e,f,g};
            tabmode.addRow(data);
            
            nos++;
        }
    }catch (SQLException e){
        System.err.println(e.getMessage());
        }
    }
    
    public void close(){
        WindowEvent closeWindow = new WindowEvent (this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    public NewInputDataAlternatif() {
        initComponents();
        datatable1();
        datatable2();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelutama = new javax.swing.JPanel();
        panelheader = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelalternatif1 = new javax.swing.JTable();
        tnis = new javax.swing.JTextField();
        labelKodeSupplier = new javax.swing.JLabel();
        tnamasiswa = new javax.swing.JTextField();
        labelKodeSupplier1 = new javax.swing.JLabel();
        labelKodeSupplier2 = new javax.swing.JLabel();
        c1 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        labelKodeSupplier3 = new javax.swing.JLabel();
        labelKodeSupplier4 = new javax.swing.JLabel();
        c3 = new javax.swing.JTextField();
        labelKodeSupplier5 = new javax.swing.JLabel();
        c4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelalternatif2 = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtDelete = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        panelheader.setBackground(new java.awt.Color(51, 51, 255));

        btnClose.setBackground(new java.awt.Color(204, 102, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_30px_4.png"))); // NOI18N
        btnClose.setContentAreaFilled(false);
        btnClose.setOpaque(true);
        btnClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_30px_5.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INPUT DATA ALTERNATIF");

        javax.swing.GroupLayout panelheaderLayout = new javax.swing.GroupLayout(panelheader);
        panelheader.setLayout(panelheaderLayout);
        panelheaderLayout.setHorizontalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelheaderLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose))
        );
        panelheaderLayout.setVerticalGroup(
            panelheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelheaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabelalternatif1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelalternatif1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tabelalternatif1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabelalternatif1.setRowHeight(30);
        tabelalternatif1.setRowMargin(2);
        tabelalternatif1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelalternatif1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelalternatif1);

        tnis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnisActionPerformed(evt);
            }
        });
        tnis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tnisKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnisKeyTyped(evt);
            }
        });

        labelKodeSupplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier.setText("NIS");
        labelKodeSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tnamasiswa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tnamasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamasiswaActionPerformed(evt);
            }
        });
        tnamasiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnamasiswaKeyTyped(evt);
            }
        });

        labelKodeSupplier1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier1.setText("NAMA SISWA");
        labelKodeSupplier1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelKodeSupplier2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier2.setText("NILAI RERATA");
        labelKodeSupplier2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        c1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        c1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c1KeyTyped(evt);
            }
        });

        c2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        c2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c2KeyTyped(evt);
            }
        });

        labelKodeSupplier3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier3.setText("SIKAP");
        labelKodeSupplier3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelKodeSupplier4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier4.setText("ABSENSI");
        labelKodeSupplier4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        c3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        c3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c3KeyTyped(evt);
            }
        });

        labelKodeSupplier5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier5.setText("EKSKUL");
        labelKodeSupplier5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        c4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        c4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c4KeyTyped(evt);
            }
        });

        tabelalternatif2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelalternatif2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tabelalternatif2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabelalternatif2.setRowHeight(30);
        tabelalternatif2.setRowMargin(2);
        tabelalternatif2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelalternatif2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelalternatif2);

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-30-w11.png"))); // NOI18N
        btnSave.setText("Simpan");
        btnSave.setContentAreaFilled(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(204, 204, 204));
        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-30-w11.png"))); // NOI18N
        btnEdit.setText("Ubah");
        btnEdit.setContentAreaFilled(false);
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setOpaque(true);
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(204, 204, 204));
        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear-30-w11.png"))); // NOI18N
        btnClear.setText("Bersih");
        btnClear.setContentAreaFilled(false);
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.setOpaque(true);
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        txtDelete.setBackground(new java.awt.Color(204, 204, 204));
        txtDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-30-w11.png"))); // NOI18N
        txtDelete.setText("Hapus");
        txtDelete.setContentAreaFilled(false);
        txtDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDelete.setOpaque(true);
        txtDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDeleteMouseExited(evt);
            }
        });
        txtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteActionPerformed(evt);
            }
        });

        btnCari.setBackground(new java.awt.Color(204, 204, 204));
        btnCari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCari.setText("NORMALISASI DAN PROSES");
        btnCari.setContentAreaFilled(false);
        btnCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCari.setOpaque(true);
        btnCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCariMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCariMouseExited(evt);
            }
        });
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelutamaLayout = new javax.swing.GroupLayout(panelutama);
        panelutama.setLayout(panelutamaLayout);
        panelutamaLayout.setHorizontalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelutamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelutamaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelutamaLayout.createSequentialGroup()
                                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelKodeSupplier2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelKodeSupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelKodeSupplier3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelKodeSupplier4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelKodeSupplier5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelutamaLayout.createSequentialGroup()
                                        .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(48, 48, 48)
                                        .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(tnamasiswa)))
                            .addGroup(panelutamaLayout.createSequentialGroup()
                                .addComponent(labelKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(tnis))))
                    .addGroup(panelutamaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
            .addGroup(panelutamaLayout.createSequentialGroup()
                .addComponent(panelheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        panelutamaLayout.setVerticalGroup(
            panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelutamaLayout.createSequentialGroup()
                .addComponent(panelheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelutamaLayout.createSequentialGroup()
                        .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tnis, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelKodeSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelKodeSupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tnamasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelutamaLayout.createSequentialGroup()
                                .addGap(136, 136, 136)
                                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE))
                            .addGroup(panelutamaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelKodeSupplier2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelKodeSupplier3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(5, 5, 5)
                                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelKodeSupplier4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelKodeSupplier5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(panelutamaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)))
                .addGroup(panelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelutamaLayout.createSequentialGroup()
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelutama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int xx, xy;
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void tabelalternatif1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelalternatif1MouseClicked
        int bar = tabelalternatif1.getSelectedRow();
        String a = tabmode.getValueAt (bar, 0).toString();
        String b = tabmode.getValueAt (bar, 1).toString();
        String c = tabmode.getValueAt (bar, 2).toString();
        String d = tabmode.getValueAt (bar, 3).toString();
        String e = tabmode.getValueAt (bar, 4).toString();
        String f = tabmode.getValueAt (bar, 5).toString();
        String g = tabmode.getValueAt (bar, 6).toString();
                
        tnis.setText(b);
        tnamasiswa.setText(c);
        c1.setText(nonDecimal.format(Double.parseDouble(d)*100));
        c2.setText(nonDecimal.format(Double.parseDouble(e)*100));
        c3.setText(nonDecimal.format(Double.parseDouble(f)*100));
        c4.setText(nonDecimal.format(Double.parseDouble(g)*100));
    }//GEN-LAST:event_tabelalternatif1MouseClicked

    private void tnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnisActionPerformed

    private void tnisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnisKeyTyped
        // TODO add your handling code here:
        char nomoraja = evt.getKeyChar();
        if (!(Character.isDigit(nomoraja) || nomoraja == KeyEvent.VK_BACK_SPACE || nomoraja == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_tnisKeyTyped

    private void tnamasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamasiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamasiswaActionPerformed

    private void tnamasiswaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnamasiswaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamasiswaKeyTyped

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void c1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c1KeyTyped
        // TODO add your handling code here:
        char nomoraja = evt.getKeyChar();
        if (!(Character.isDigit(nomoraja) || nomoraja == KeyEvent.VK_BACK_SPACE || nomoraja == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_c1KeyTyped

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void c2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c2KeyTyped
        // TODO add your handling code here:
        char nomoraja = evt.getKeyChar();
        if (!(Character.isDigit(nomoraja) || nomoraja == KeyEvent.VK_BACK_SPACE || nomoraja == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_c2KeyTyped

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void c3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c3KeyTyped
        // TODO add your handling code here:
        char nomoraja = evt.getKeyChar();
        if (!(Character.isDigit(nomoraja) || nomoraja == KeyEvent.VK_BACK_SPACE || nomoraja == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_c3KeyTyped

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c4ActionPerformed

    private void c4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c4KeyTyped
        // TODO add your handling code here:
        char nomoraja = evt.getKeyChar();
        if (!(Character.isDigit(nomoraja) || nomoraja == KeyEvent.VK_BACK_SPACE || nomoraja == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_c4KeyTyped

    private void tabelalternatif2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelalternatif2MouseClicked
        // TODO add your handling code here:
        int bar = tabelalternatif2.getSelectedRow();
        String a = tabmode.getValueAt (bar, 1).toString();
        String b = tabmode.getValueAt (bar, 2).toString();
        String c = tabmode.getValueAt (bar, 3).toString();
        String d = tabmode.getValueAt (bar, 4).toString();
        String e = tabmode.getValueAt (bar, 5).toString();
        String f = tabmode.getValueAt (bar, 6).toString();
        
        tnis.setText(a);
        tnamasiswa.setText(b);
        c1.setText(c);
        c2.setText(d);
        c3.setText(e);
        c4.setText(f);
    }//GEN-LAST:event_tabelalternatif2MouseClicked

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        btnSave.setBackground(new Color(0,0,204));
        btnSave.setForeground(Color.white);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        btnSave.setBackground(new Color(204,204,204));
        btnSave.setForeground(Color.black);
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         try{
            // Prepare the SQL query
            String selectQuery = "SELECT nis FROM tb_alternatif1 WHERE nis = ?";
            PreparedStatement selectStatement = conn.prepareStatement(selectQuery);
            selectStatement.setString(1, tnis.getText());

            // Execute the query
            ResultSet resultSet = selectStatement.executeQuery();

            // Check if a record with the id already exists
            if (resultSet.next()) {
                // Throw an error or handle the situation accordingly
                JOptionPane.showMessageDialog(null, "NIS " +tnis.getText()+ " sudah ada.");
                throw new RuntimeException("Record with id " + tnis.getText() + " already exists.");
            } else {
                // Proceed with the insert operation
                String sql1 = "insert into tb_alternatif1 values (?,?,?,?,?,?,?)";
                PreparedStatement stat = conn.prepareStatement(sql1);
                stat.setString(1, null);
                stat.setString(2, tnis.getText());
                stat.setString(3, tnamasiswa.getText());
                stat.setString(4, c1.getText());
                stat.setString(5, c2.getText());           
                stat.setString(6, c3.getText());
                stat.setString(7, c4.getText());

                stat.executeUpdate();
                
                String sql2 = "insert into tb_alternatif2 values (?,?,?,?,?,?,?)";
                
                double c1Double = Double.parseDouble(c1.getText()) / 100;
                double c2Double = Double.parseDouble(c2.getText()) / 100;
                double c3Double = Double.parseDouble(c3.getText()) / 100;
                double c4Double = Double.parseDouble(c4.getText()) / 100;            
            
                PreparedStatement stats = conn.prepareStatement(sql2);
                stats.setString(1, null);
                stats.setString(2, tnis.getText());
                stats.setString(3, tnamasiswa.getText());
                stats.setString(4, String.valueOf(c1Double));
                stats.setString(5, String.valueOf(c2Double));           
                stats.setString(6, String.valueOf(c3Double));
                stats.setString(7, String.valueOf(c4Double));

                stats.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
                kosong();
                tnis.requestFocus();
                datatable1();
                datatable2();
            }
            
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
            System.err.println(e.getMessage());
        }   
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        btnEdit.setBackground(new Color(0,0,204));
        btnEdit.setForeground(Color.white);
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        btnEdit.setBackground(new Color(204,204,204));
        btnEdit.setForeground(Color.black);
    }//GEN-LAST:event_btnEditMouseExited

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try{
            String sql = "UPDATE tb_alternatif1 SET nama=?, c1=?, c2=?, c3 =?, c4=? WHERE nis = ?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tnamasiswa.getText());
            stat.setString(2, c1.getText());
            stat.setString(3, c2.getText());
            stat.setString(4, c3.getText());
            stat.setString(5, c4.getText());
            stat.setString(6, tnis.getText());
            
            String sql2 = "UPDATE tb_alternatif2 SET nama=?, c1=?, c2=?, c3 =?, c4=? WHERE nis = ?";
            PreparedStatement stats = conn.prepareStatement(sql2);
            
            double c1Double = Double.parseDouble(c1.getText()) / 100;
            double c2Double = Double.parseDouble(c2.getText()) / 100;
            double c3Double = Double.parseDouble(c3.getText()) / 100;
            double c4Double = Double.parseDouble(c4.getText()) / 100;
            
            stats.setString(1, tnamasiswa.getText());
            stats.setString(2, String.valueOf(c1Double));
            stats.setString(3, String.valueOf(c2Double));
            stats.setString(4, String.valueOf(c3Double));
            stats.setString(5, String.valueOf(c4Double));
            stats.setString(6, tnis.getText());
            
            stat.executeUpdate();
            stats.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil diubah");
            kosong();
            tnis.requestFocus();
            datatable1();
            datatable2();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah"+e);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        btnClear.setBackground(new Color(0,0,204));
        btnClear.setForeground(Color.white);
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        btnClear.setBackground(new Color(204,204,204));
        btnClear.setForeground(Color.black);
    }//GEN-LAST:event_btnClearMouseExited

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDeleteMouseEntered
        txtDelete.setBackground(Color.red);
        txtDelete.setForeground(Color.white);
    }//GEN-LAST:event_txtDeleteMouseEntered

    private void txtDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDeleteMouseExited
        txtDelete.setBackground(new Color(204,204,204));
        txtDelete.setForeground(Color.black);
    }//GEN-LAST:event_txtDeleteMouseExited

    private void txtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteActionPerformed
        int ok = JOptionPane.showConfirmDialog(null,"Hapus","Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if (ok==0){
            String sql = "DELETE from tb_alternatif1 WHERE nis = '"+tnis.getText()+"' ";
            String sql2 = "DELETE from tb_alternatif2 WHERE nis = '"+tnis.getText()+"' ";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                PreparedStatement stats = conn.prepareStatement(sql2);
                stat.executeUpdate();
                stats.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                kosong();
                tnis.requestFocus();
                datatable1();
                datatable2();
        } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus"+e);
            }
        }     
    }//GEN-LAST:event_txtDeleteActionPerformed

    private void btnCariMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariMouseEntered
        btnCari.setBackground(new Color(0,0,204));
        btnCari.setForeground(Color.white);
    }//GEN-LAST:event_btnCariMouseEntered

    private void btnCariMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariMouseExited
        btnCari.setBackground(new Color(204,204,204));
        btnCari.setForeground(Color.black);
    }//GEN-LAST:event_btnCariMouseExited

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        //buka menu proses
        ModelAlternatifSAW.deleteAllRowSAW();
        close();
        NewHasil nh = new NewHasil();
        nh.setVisible(true);
    }//GEN-LAST:event_btnCariActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void tnisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnisKeyPressed
        // TODO add your handling code here:
        String sql = "select * from tabelsiswa where nis = '"+tnis.getText()+"'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String nama = hasil.getString("nama_siswa");
                tnamasiswa.setText(nama);
                tnamasiswa.setEnabled(false);
            }
        } catch (Exception e) {}
    }//GEN-LAST:event_tnisKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewInputDataAlternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewInputDataAlternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewInputDataAlternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewInputDataAlternatif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewInputDataAlternatif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JTextField c4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelKodeSupplier;
    private javax.swing.JLabel labelKodeSupplier1;
    private javax.swing.JLabel labelKodeSupplier2;
    private javax.swing.JLabel labelKodeSupplier3;
    private javax.swing.JLabel labelKodeSupplier4;
    private javax.swing.JLabel labelKodeSupplier5;
    private javax.swing.JPanel panelheader;
    private javax.swing.JPanel panelutama;
    private javax.swing.JTable tabelalternatif1;
    private javax.swing.JTable tabelalternatif2;
    private javax.swing.JTextField tnamasiswa;
    private javax.swing.JTextField tnis;
    private javax.swing.JButton txtDelete;
    // End of variables declaration//GEN-END:variables
}
