/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import connectionDB.koneksi;
import java.awt.event.ActionEvent;
import static views.MenuUtama.maximixed;
/**
 *
 * @author User
 */
public class NewMasterDataSiswa extends javax.swing.JFrame {

    /**
     * Creates new form NewMasterDataSiswa
     */
    
    public NewMasterDataSiswa (java.awt.Frame parent, boolean modal) {
        initComponents();
        datatable();
        aktif();
    }
    
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    
    protected void aktif(){
        tnis.setEnabled(true);
        tnisn.setEnabled(true);
        tnama.setEnabled(true);
        ttempat.setEnabled(true);
        talm.setEnabled(true);
        ttlp.setEnabled(true);
        temail.setEnabled(true);
    
        tnis.requestFocus();
    }
    
    protected void kosong(){
        tnis.setText("");
        tnisn.setText("");
        tnama.setText("");
        ttempat.setText("");
        date_siswa.setDate(null);
        talm.setText("");
        rjk1.setSelected(false);
        cagama.setSelectedIndex(0);
        cjurusan.setSelectedIndex(0);
        ckelas.setSelectedIndex(0);
        ttlp.setText("");
        temail.setText("");
        
        tcari.setText("");
    }
    
    String Tgl_lahir;
    public void tanggal(){
        if (date_siswa.getDate() !=null){
            String pattern = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(pattern);
            Tgl_lahir = String.valueOf(format.format(date_siswa.getDate()));
        }
    }
    
    public void tanggal_lahir() {
        try {
            String sql = "Select * from tabelsiswa where nis='"+tnis.getText()+"'";
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                date_siswa.setDate(hasil.getDate("tanggal_lahir_siswa"));
            }
        }catch (SQLException ex){}
    }
    
    protected void datatable(){
    Object [] Baris = {"NIS","NISN","NAMA","TEMPAT LAHIR","TANGGAL LAHIR","ALAMAT","KELAMIN","AGAMA","JURUSAN","KELAS","TLP","EMAIL"};
    tabmode = new DefaultTableModel(null, Baris);
    tabelsiswa.setModel(tabmode);
    String cari = tcari.getText();
    try {
    String sql = "Select * from tabelsiswa where nama_siswa like '%"+cari+"%' "
            + "or kelas_siswa like '%"+cari+"%' or jurusan_siswa like '%"+cari+"%' "
            + "or alamat_siswa like '%"+cari+"%' or nisn like '%"+cari+"%'"
            + "or jenis_kelamin_siswa like '%"+cari+"%' or agama_siswa like '%"+cari+"%' "
            + "ORDER BY nis";
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()){
            String a = hasil.getString("nis");
            String b = hasil.getString("nisn");
            String c = hasil.getString("nama_siswa");
            String d = hasil.getString("tempat_lahir_siswa");
            String e = hasil.getString("tanggal_lahir_siswa");
            String f = hasil.getString("alamat_siswa");
            String g = hasil.getString("jenis_kelamin_siswa");
            String h = hasil.getString("agama_siswa");
            String i = hasil.getString("jurusan_siswa");
            String j = hasil.getString("kelas_siswa");
            String k = hasil.getString("no_telp_siswa");
            String l = hasil.getString("email_siswa");
            
            String[] data={a,b,c,d,e,f,g,h,i,j,k,l};
            tabmode.addRow(data);
        }
    }catch (Exception e){
        }
    }
    
    public NewMasterDataSiswa() {
        initComponents();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelKodeSupplier = new javax.swing.JLabel();
        tnis = new javax.swing.JTextField();
        tnisn = new javax.swing.JTextField();
        labelKodeSupplier1 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        labelKodeSupplier2 = new javax.swing.JLabel();
        ttempat = new javax.swing.JTextField();
        labelKodeSupplier3 = new javax.swing.JLabel();
        date_siswa = new com.toedter.calendar.JDateChooser();
        labelKodeSupplier4 = new javax.swing.JLabel();
        talm = new javax.swing.JTextField();
        labelKodeSupplier5 = new javax.swing.JLabel();
        labelKodeSupplier6 = new javax.swing.JLabel();
        rjk1 = new javax.swing.JRadioButton();
        rjk2 = new javax.swing.JRadioButton();
        cagama = new javax.swing.JComboBox<>();
        cjurusan = new javax.swing.JComboBox<>();
        labelKodeSupplier8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelsiswa = new javax.swing.JTable();
        labelKodeSupplier9 = new javax.swing.JLabel();
        ckelas = new javax.swing.JComboBox<>();
        ttlp = new javax.swing.JTextField();
        labelKodeSupplier10 = new javax.swing.JLabel();
        labelKodeSupplier11 = new javax.swing.JLabel();
        temail = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        labelKodeSupplier12 = new javax.swing.JLabel();
        tcari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        btnClose.setBackground(new java.awt.Color(204, 102, 255));
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_30px_4.png"))); // NOI18N
        btnClose.setContentAreaFilled(false);
        btnClose.setOpaque(true);
        btnClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Delete_30px_5.png"))); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA SISWA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        labelKodeSupplier.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier.setText("NIS");
        labelKodeSupplier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tnis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tnis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnisActionPerformed(evt);
            }
        });
        tnis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnisKeyTyped(evt);
            }
        });

        tnisn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tnisn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnisnActionPerformed(evt);
            }
        });
        tnisn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tnisnKeyTyped(evt);
            }
        });

        labelKodeSupplier1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier1.setText("NISN");
        labelKodeSupplier1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamaActionPerformed(evt);
            }
        });

        labelKodeSupplier2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier2.setText("NAMA");
        labelKodeSupplier2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ttempat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ttempat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttempatActionPerformed(evt);
            }
        });

        labelKodeSupplier3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier3.setText("TEMPAT LAHIR");
        labelKodeSupplier3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        date_siswa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        labelKodeSupplier4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier4.setText("TANGGAL LAHIR");
        labelKodeSupplier4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        talm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        talm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                talmActionPerformed(evt);
            }
        });

        labelKodeSupplier5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier5.setText("ALAMAT");
        labelKodeSupplier5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelKodeSupplier6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier6.setText("JENIS KELAMIN");
        labelKodeSupplier6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        rjk1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rjk1.setText("Laki - Laki");

        rjk2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rjk2.setText("Perempuan");

        cagama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Satu", "ISLAM", "KRISTEN", "KATOLIK", "BUDDHA", "HINDU", "KONGHUCU" }));

        cjurusan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cjurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Satu", "DKV", "Perkantoran", "Akuntansi", "Pemasaran" }));

        labelKodeSupplier8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier8.setText("JURUSAN");
        labelKodeSupplier8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tabelsiswa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabelsiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabelsiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabelsiswa.setRowHeight(30);
        tabelsiswa.setRowMargin(2);
        tabelsiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelsiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelsiswa);

        labelKodeSupplier9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier9.setText("KELAS");
        labelKodeSupplier9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ckelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Satu", "10", "11", "12" }));

        ttlp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ttlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttlpActionPerformed(evt);
            }
        });
        ttlp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ttlpKeyTyped(evt);
            }
        });

        labelKodeSupplier10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier10.setText("NO TLP");
        labelKodeSupplier10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelKodeSupplier11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier11.setText("EMAIL");
        labelKodeSupplier11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        temail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        temail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temailActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(204, 204, 204));
        btnSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-30-w11.png"))); // NOI18N
        btnSave.setText("Simpan");
        btnSave.setContentAreaFilled(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setOpaque(true);
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(204, 204, 204));
        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-30-w11.png"))); // NOI18N
        btnEdit.setText("Ubah");
        btnEdit.setContentAreaFilled(false);
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setOpaque(true);
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
        });
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtDelete.setBackground(new java.awt.Color(204, 204, 204));
        txtDelete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete-30-w11.png"))); // NOI18N
        txtDelete.setText("Hapus");
        txtDelete.setContentAreaFilled(false);
        txtDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDelete.setOpaque(true);
        txtDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtDeleteMouseExited(evt);
            }
        });
        txtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(204, 204, 204));
        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clear-30-w11.png"))); // NOI18N
        btnClear.setText("Bersih");
        btnClear.setContentAreaFilled(false);
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.setOpaque(true);
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        labelKodeSupplier12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelKodeSupplier12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier12.setText("AGAMA");
        labelKodeSupplier12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tcari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcariActionPerformed(evt);
            }
        });

        btnCari.setBackground(new java.awt.Color(204, 204, 204));
        btnCari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCari.setText("Pencarian");
        btnCari.setContentAreaFilled(false);
        btnCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCari.setOpaque(true);
        btnCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCariMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCariMouseExited(evt);
            }
        });
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelKodeSupplier2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tnama))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelKodeSupplier3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ttempat))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelKodeSupplier5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(talm, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelKodeSupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tnisn))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tnis))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelKodeSupplier4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(date_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit)
                                .addGap(18, 18, 18)
                                .addComponent(txtDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnClear)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelKodeSupplier6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rjk1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rjk2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelKodeSupplier12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelKodeSupplier8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelKodeSupplier9, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelKodeSupplier10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelKodeSupplier11, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cagama, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ckelas, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ttlp, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnCari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnis, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKodeSupplier6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rjk1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rjk2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodeSupplier1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnisn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKodeSupplier12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cagama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodeSupplier2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tnama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cjurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKodeSupplier8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodeSupplier3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ttempat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKodeSupplier9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckelas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelKodeSupplier4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelKodeSupplier10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ttlp, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(date_siswa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodeSupplier5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(talm, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKodeSupplier11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tcari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int xx, xy;
    private void tnisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnisActionPerformed

    private void tnisnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnisnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnisnActionPerformed

    private void tnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamaActionPerformed

    private void ttempatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttempatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttempatActionPerformed

    private void talmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_talmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_talmActionPerformed

    private void tabelsiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelsiswaMouseClicked
        int bar = tabelsiswa.getSelectedRow();
        String a = tabmode.getValueAt (bar, 0).toString();
        String b = tabmode.getValueAt (bar, 1).toString();
        String c = tabmode.getValueAt (bar, 2).toString();
        String d = tabmode.getValueAt (bar, 3).toString();
        String e = tabmode.getValueAt (bar, 4).toString();
        String f = tabmode.getValueAt (bar, 5).toString();
        String g = tabmode.getValueAt (bar, 6).toString();
        String h = tabmode.getValueAt (bar, 7).toString();
        String i = tabmode.getValueAt (bar, 8).toString();
        String j = tabmode.getValueAt (bar, 9).toString();
        String k = tabmode.getValueAt (bar, 10).toString();
        String l = tabmode.getValueAt (bar, 11).toString();
        
        tnis.setText(a);
        tnisn.setText(b);
        tnama.setText(c);
        ttempat.setText(d);
        tanggal_lahir();
        talm.setText(f);
        
        if(g.equals("Laki-Laki")) {rjk1.setSelected(true); rjk2.setSelected(false);}
        else {rjk1.setSelected(false); rjk2.setSelected(true);}
        
        cagama.setSelectedItem(h);
        cjurusan.setSelectedItem(i);
        ckelas.setSelectedItem(j);
        ttlp.setText(k);
        temail.setText(l);
    }//GEN-LAST:event_tabelsiswaMouseClicked

    private void ttlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttlpActionPerformed

    private void temailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temailActionPerformed

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered
        btnSave.setBackground(new Color(0,0,204));
        btnSave.setForeground(Color.white);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        btnSave.setBackground(new Color(204,204,204));
        btnSave.setForeground(Color.black);
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(date_siswa.getDate()));
        
        String sql = "insert into tabelsiswa values (?,?,?,?,?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tnis.getText());
            stat.setString(2, tnisn.getText());
            stat.setString(3, tnama.getText());
            stat.setString(4, ttempat.getText());
            stat.setString(5, tanggal);
            stat.setString(6, talm.getText());
            
            String jkel="";
            if(rjk1.isSelected()) jkel="Laki-Laki";
            else jkel="Perempuan";
            stat.setString(7, jkel);
            
            stat.setString(8, cagama.getSelectedItem().toString());
            stat.setString(9, cjurusan.getSelectedItem().toString());
            stat.setString(10, ckelas.getSelectedItem().toString());
            
            stat.setString(11, ttlp.getText());
            stat.setString(12, temail.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            tnis.requestFocus();
            datatable();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        btnEdit.setBackground(new Color(0,0,204));
        btnEdit.setForeground(Color.white);
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        btnEdit.setBackground(new Color(204,204,204));
        btnEdit.setForeground(Color.black);
    }//GEN-LAST:event_btnEditMouseExited

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal  = String.valueOf(fm.format(date_siswa.getDate()));
        
        try{
            String sql = "update tabelsiswa set nisn=?,nama_siswa=?,tempat_lahir_siswa=?,tanggal_lahir_siswa=?,alamat_siswa=?,jenis_kelamin_siswa=?,agama_siswa=?,jurusan_siswa=?,kelas_siswa=?,no_telp_siswa=?,email_siswa=? where nis=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tnisn.getText());
            stat.setString(2, tnama.getText());
            stat.setString(3, ttempat.getText());
            stat.setString(4, tanggal);
            stat.setString(5, talm.getText());
            
            String jkel="";
            if (rjk1.isSelected()) jkel="Laki-Laki";
            else jkel="Perempuan";
            stat.setString(6, jkel);
            
            stat.setString(7, cagama.getSelectedItem().toString());
            stat.setString(8, cjurusan.getSelectedItem().toString());
            stat.setString(9, ckelas.getSelectedItem().toString());
            
            stat.setString(10, ttlp.getText());
            stat.setString(11, temail.getText());
            stat.setString(12, tnis.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil diubah");
            kosong();
            tnis.requestFocus();
            datatable();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah"+e);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDeleteMouseEntered
        txtDelete.setBackground(Color.red);
        txtDelete.setForeground(Color.white);
    }//GEN-LAST:event_txtDeleteMouseEntered

    private void txtDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDeleteMouseExited
        txtDelete.setBackground(new Color(204,204,204));
        txtDelete.setForeground(Color.black);
    }//GEN-LAST:event_txtDeleteMouseExited

    private void txtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteActionPerformed
        int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql="delete from tabelsiswa where nis='"+tnis.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                tnis.requestFocus();
                datatable();
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus"+e);
            }
        }
    }//GEN-LAST:event_txtDeleteActionPerformed

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        btnClear.setBackground(new Color(0,0,204));
        btnClear.setForeground(Color.white);
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        btnClear.setBackground(new Color(204,204,204));
        btnClear.setForeground(Color.black);
    }//GEN-LAST:event_btnClearMouseExited

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcariActionPerformed

    private void btnCariMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariMouseEntered
        btnCari.setBackground(new Color(0,0,204));
        btnCari.setForeground(Color.white);
    }//GEN-LAST:event_btnCariMouseEntered

    private void btnCariMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariMouseExited
        btnCari.setBackground(new Color(204,204,204));
        btnCari.setForeground(Color.black);
    }//GEN-LAST:event_btnCariMouseExited

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        datatable();
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    private void tnisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnisKeyTyped
        // TODO add your handling code here:
        char nomoraja = evt.getKeyChar();
        if (!(Character.isDigit(nomoraja) || nomoraja == KeyEvent.VK_BACK_SPACE || nomoraja == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_tnisKeyTyped

    private void tnisnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tnisnKeyTyped
        // TODO add your handling code here:
        char nomoraja = evt.getKeyChar();
        if (!(Character.isDigit(nomoraja) || nomoraja == KeyEvent.VK_BACK_SPACE || nomoraja == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_tnisnKeyTyped

    private void ttlpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ttlpKeyTyped
        // TODO add your handling code here:
        char nomoraja = evt.getKeyChar();
        if (!(Character.isDigit(nomoraja) || nomoraja == KeyEvent.VK_BACK_SPACE || nomoraja == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_ttlpKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMasterDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMasterDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMasterDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMasterDataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMasterDataSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cagama;
    private javax.swing.JComboBox<String> cjurusan;
    private javax.swing.JComboBox<String> ckelas;
    private com.toedter.calendar.JDateChooser date_siswa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelKodeSupplier;
    private javax.swing.JLabel labelKodeSupplier1;
    private javax.swing.JLabel labelKodeSupplier10;
    private javax.swing.JLabel labelKodeSupplier11;
    private javax.swing.JLabel labelKodeSupplier12;
    private javax.swing.JLabel labelKodeSupplier2;
    private javax.swing.JLabel labelKodeSupplier3;
    private javax.swing.JLabel labelKodeSupplier4;
    private javax.swing.JLabel labelKodeSupplier5;
    private javax.swing.JLabel labelKodeSupplier6;
    private javax.swing.JLabel labelKodeSupplier8;
    private javax.swing.JLabel labelKodeSupplier9;
    private javax.swing.JRadioButton rjk1;
    private javax.swing.JRadioButton rjk2;
    private javax.swing.JTable tabelsiswa;
    private javax.swing.JTextField talm;
    private javax.swing.JTextField tcari;
    private javax.swing.JTextField temail;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnis;
    private javax.swing.JTextField tnisn;
    private javax.swing.JTextField ttempat;
    private javax.swing.JTextField ttlp;
    private javax.swing.JButton txtDelete;
    // End of variables declaration//GEN-END:variables
}
